// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketsLayer.DAL.Context;

#nullable disable

namespace TicketsLayer.DAL.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20230321162449_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.Property<int>("DevelopersId")
                        .HasColumnType("int");

                    b.Property<int>("IssuesId")
                        .HasColumnType("int");

                    b.HasKey("DevelopersId", "IssuesId");

                    b.HasIndex("IssuesId");

                    b.ToTable("DeveloperTicket");
                });

            modelBuilder.Entity("TicketsLayer.DAL.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Automotive & Baby"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty & Health"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("TicketsLayer.DAL.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentID = 1,
                            FirstName = "Freddie",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("Your_Project_Name.Models.Domain.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dept_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dept_id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Dept_id = 2,
                            Description = "Harum hic impedit dolore voluptate placeat.",
                            IsClosed = true,
                            Severity = 1,
                            Title = "in"
                        },
                        new
                        {
                            Id = 1,
                            Dept_id = 1,
                            Description = "Rerum totam est quo possimus sunt sunt ad.",
                            IsClosed = false,
                            Severity = 0,
                            Title = "id"
                        },
                        new
                        {
                            Id = 2,
                            Dept_id = 3,
                            Description = "Id cumque explicabo beatae.",
                            IsClosed = false,
                            Severity = 1,
                            Title = "dicta"
                        },
                        new
                        {
                            Id = 3,
                            Dept_id = 2,
                            Description = "Consectetur beatae dolorem voluptates occaecati.",
                            IsClosed = false,
                            Severity = 0,
                            Title = "eius"
                        },
                        new
                        {
                            Id = 4,
                            Dept_id = 1,
                            Description = "Nulla est doloribus ut non aspernatur vero dolores.",
                            IsClosed = false,
                            Severity = 2,
                            Title = "assumenda"
                        },
                        new
                        {
                            Id = 5,
                            Dept_id = 2,
                            Description = "Et praesentium est ipsum eligendi rerum itaque voluptate quia.",
                            IsClosed = false,
                            Severity = 1,
                            Title = "ex"
                        },
                        new
                        {
                            Id = 6,
                            Dept_id = 3,
                            Description = "Optio non debitis ut molestiae dolorem ad.",
                            IsClosed = false,
                            Severity = 2,
                            Title = "velit"
                        });
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.HasOne("TicketsLayer.DAL.Models.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Your_Project_Name.Models.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketsLayer.DAL.Models.Developer", b =>
                {
                    b.HasOne("TicketsLayer.DAL.Models.Department", "Department")
                        .WithMany("Developers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Your_Project_Name.Models.Domain.Ticket", b =>
                {
                    b.HasOne("TicketsLayer.DAL.Models.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("Dept_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TicketsLayer.DAL.Models.Department", b =>
                {
                    b.Navigation("Developers");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
